version: '3.8'

services:
  car-qa:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./vector_db:/app/vector_db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3 