services:
  car-qa:
    build: .
    image: emirhnslspr/car-review-qa:v1.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./articles:/app/articles
      - ./vector_db:/app/vector_db
      - ./src:/app/src
    env_file:
      - .env 
    environment:
      - PYTHONPATH=/app/src
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3 